name: Android CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean React Native project directory
        run: |
          cd mobile/ConectameApp
          git clean -fdx # Cleans untracked files and directories, ensuring a pristine state.

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js 20, as the project was created with a compatible version

      - name: Install npm dependencies
        run: |
          cd mobile/ConectameApp
          npm install

      - name: Clear Metro cache
        run: |
          cd mobile/ConectameApp
          rm -rf ./.metro
          rm -rf ./node_modules/.cache

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: |
          cd mobile/ConectameApp/android
          chmod +x gradlew

      - name: Build Android Release APK
        run: |
          cd mobile/ConectameApp/android
          ./gradlew assembleRelease

      - name: Upload Release APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: mobile/ConectameApp/android/app/build/outputs/apk/release/app-release.apk
